name: Wpm

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Log in to Azure and ACR
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          enable-AzPSSession: true
      
      - name: 'Build and push container image'
        run: |
          docker build src -f src/Wpm.Management.Api/Dockerfile -t ${{secrets.ACR_LOGIN_SERVER}}/wpm-management-api:${{github.sha}}
          docker push ${{ secrets.ACR_LOGIN_SERVER }}/wpm-management-api:${{ github.sha }}
